/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.project2;

import bitcamp.project2.util.Prompt;
import bitcamp.project2.command.TodayTodoCommand;
import bitcamp.project2.command.TodoCommand;
import bitcamp.project2.vo.TodoList;


public class App {
    TodoList todoList = new TodoList();
    TodoCommand todoCommand = new TodoCommand(todoList);
    TodayTodoCommand todayTodoCommand = new TodayTodoCommand(todoList);

    String[] menus = {"오늘의 할 일", "할 일 추가", "할 일 완료", "할 일 목록", "할 일 수정", "할 일 삭제", "전체 통계", "종료"};

    public void printMenu() {
        System.out.println("==========[TodoList]==========");
        for (int i = 0; i < menus.length; i++) {
            System.out.printf("%d. %s\n", (i + 1), menus[i]);
        }
        System.out.println("==============================");
    }

    public void run() {
        todoList.testData();
        printMenu();
        while (true) {
            String choice = Prompt.input("메뉴 >");
            if(choice.equals("menu")){
                printMenu();
                continue;
            }
            try {
                int menuNo = Integer.parseInt(choice);
                if (isAvailable(menuNo)) {
                    System.out.println("없는 메뉴입니다. 재입력해주세요.");
                    continue;
                }
                String menuTitle = menus[menuNo - 1];
                switch (menuTitle) {
                    case "오늘의 할 일" :
                        todayTodoCommand.executeToday();
                    case "할 일 추가":
                        todoCommand.toDo();
                        break;
                    case "할 일 완료":
                        todoCommand.completeTask();
                        break;
                    case "할 일 목록":
                        todoCommand.viewTasks(); // 조회에서는 번호 없이 출력
                        break;
                    case "할 일 수정":
                        todoCommand.updateTask();
                        break;
                    case "할 일 삭제":
                        todoCommand.deleteTask();
                        break;
                    case "전체 통계" : todoCommand.rateTask(); break;
                    case "종료":
                        System.out.println("종료");
                        return;
                }
            } catch (NumberFormatException e) {
                System.out.println("올바른 숫자를 입력해주세요.");
            }
        }
    }

    public static void main(String[] args) {
        App app = new App();
        app.run();
    }

    private boolean isAvailable(int number) {
        return number < 1 || number > menus.length;
    }
}
